name: CI CD

on:
  push:
    branches:
     - '*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      RunPublish:
        description: 'Should run publish'
        required: true
        default: 'false'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: echo "Build the Artifacts"
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Publish
      run: echo "Publish the Artifacts"
  DeployDEV:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    needs: publish
    environment:
      name: DEV
    steps:
    - name: Deploy
      run: echo "Deploy to Dev Environment"
  DeploySTG:
    name: Deploy to STG
    runs-on: ubuntu-latest
    needs: DeployDEV
    environment:
      name: STG
    steps:
    - name: Deploy
      run: echo "Deploy to PRD Environment"
  DeployPRD:
    name: Deploy to PRD
    runs-on: ubuntu-latest
    needs: DeploySTG
    environment:
      name: PRD
    steps:
    - name: Deploy
      run: echo "Deploy to PRD Environment"
