name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      RunPublish:
        description: 'Should run publish'
        required: true
        default: 'false'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: echo "Build the Artifacts"
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Publish
      run: echo "Publish the Artifacts"
  DeployDev:
    runs-on: ubuntu-latest
    needs: publish
    environment:
      name: Dev
    steps:
    - name: Deploy
      run: echo "Deploy to Dev Environment"
  DeployPRD:
    runs-on: ubuntu-latest
    needs: publish
    environment:
      name: PRD
    steps:
    - name: Deploy
      run: echo "Deploy to PRD Environment"
