name: Build

# env:
#   BUILD_NUMBER: 'Bw.API.Assist'

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      RunPublish:
        description: 'Should run publish'
        required: true
        default: 'false'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
#     - uses: actions/checkout@v2
#     - name: Get Build Version
#       run: |
#         Import-Module ./.github/workflows/scripts/GetBuildVersion.psm1
#         Write-Host $Env:GITHUB_REF
#         $version = GetBuildVersion -VersionString $Env:GITHUB_REF
#         echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
#       shell: pwsh
#     - name: Build Version
#       run: echo $BUILD_VERSION
#     - name: Github Run ID
#       run: echo $GITHUB_RUN_ID
    - name: Generate Build Number
      run: |
        $version_number = [System.TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([datetime]::UtcNow, 'Australia/Sydney').ToString('yyMM.ddHH.mmss')
        echo $version_number
        echo "BUILD_NUMBER=$version_number" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh
    - name: show buid number
      run: echo ${{env.BUILD_NUMBER}}
  Deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: show buid number
      run: echo ${{env.BUILD_NUMBER}}
#       shell: pwsh
#     - name: Setup .NET
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: 5.0.x
#     - name: Restore dependencies
#       run: dotnet restore
#     - name: Build
#       run: dotnet build --no-restore
