name: Build

# env:
#   BUILD_NUMBER: 'Bw.API.Assist'

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      RunPublish:
        description: 'Should run publish'
        required: true
        default: 'false'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.generateBuildNumber.outputs.buildNumber}}
    steps:
    - name: Generate Build Number
      id: generateBuildNumber
      run: |
        $version_number = [System.TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([datetime]::UtcNow, 'Australia/Sydney').ToString('yyMM.ddHH.mmss')
        echo $version_number
        echo "::set-output name=buildNumber::$version_number"
      shell: pwsh
  Deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: show buid number
      run: echo ${{needs.build.outputs.output1}}
#       shell: pwsh
#     - name: Setup .NET
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: 5.0.x
#     - name: Restore dependencies
#       run: dotnet restore
#     - name: Build
#       run: dotnet build --no-restore
